# -*- coding: utf-8 -*-
"""final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xuep4Mx_UgxWmnujKfqh7wMElxLqzfE_
"""

# ⚡ Ultra-Fast AI Ad Expert v4.0 — Single Gemini Call, No Delays

!pip install -q -U google-genai
from google.colab import userdata, files
import google.generativeai as genai
from PIL import Image
from IPython.display import display

# Setup Gemini
genai.configure(api_key=userdata.get("api_key"))
model = genai.GenerativeModel("gemini-2.0-flash")

# Inputs
campaign = input("👋 Hello! I'm your AI Ad Expert.\n🎯 Choose your Campaign Type (Awareness / Engagement / Sales): ").strip().lower()
product = input("Product/Service: ").strip()
platform = input("Platform (Facebook / Google / Instagram / LinkedIn): ").strip().lower()
ad_format = input("Ad Format (Image / Video / Carousel / Story): ").strip().lower()
budget = input("Budget (e.g., 5000 PKR / 100 USD): ").strip()
area = input("Target city/ Area: ").strip()
img_choice = input("Analyze poster? (upload / url / skip): ").strip().lower()

poster_review_text = ""

if img_choice == "upload":
    uploaded = files.upload()
    for filename in uploaded.keys():
        image = Image.open(filename)
        display(image)
        image_input = "User uploaded a poster for review."
elif img_choice == "url":
    img_url = input("Paste Image URL: ").strip()
    image_input = f"Poster URL: {img_url}"
else:
    image_input = "No poster provided."

# ✅ SINGLE FAST API CALL — Generates AD PLAN + POSTER REVIEW in one call
prompt = f"""
You are an elite ad strategist. Use this data to generate output:

Product: {product}
Campaign: {campaign}
Platform: {platform}
Budget: {budget}
Area: {area}
Format: {ad_format}
Poster Input: {image_input}

1️⃣ First, give this in EXACT format:
1. Target People: (1 short line)
2. CTA Idea: (1 short line)
3. Caption: (max 12 words, catchy)
4. Hashtags: #Keyword1, #Keyword2, #Keyword3, #Keyword4, #Keyword5
5. Smart Tip: (1 short improvement tip)

2️⃣ Then, if poster provided, analyze it in exactly 4 lines:
✔ Good: (1 point)
⚙ Improve: (1 point)
🎯 Why: (1 reason)
🎨 Color Tip: (1 suggestion)

If no poster: write "Poster Review: Skipped".
"""

response = model.generate_content(prompt).text.strip()

print("\n================ RESULT ================")
print(response)
print("========================================")